# Generated by Django 4.2.4 on 2023-08-08 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel1', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
                ('decricao_curta', models.CharField(blank=True, max_length=50, null=True)),
                ('decricao_maior', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel2', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
                ('decricao_curta', models.CharField(blank=True, max_length=50, null=True)),
                ('decricao_maior', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel3', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
                ('decricao_curta', models.CharField(blank=True, max_length=50, null=True)),
                ('decricao_maior', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemLateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='ImagensDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgDestaque1', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='TabsContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabscontato', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='TabsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabsinfo', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='TabsPalestras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabspalestra', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Topo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_topo', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('url', embed_video.fields.EmbedVideoField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
