# Generated by Django 4.2.4 on 2023-08-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carroucel1', models.ImageField(upload_to='imagens')),
                ('carroucel2', models.ImageField(upload_to='imagens')),
                ('carroucel3', models.ImageField(upload_to='imagens')),
                ('img_1', models.ImageField(upload_to='imagens')),
                ('img_2', models.ImageField(upload_to='imagens')),
            ],
        ),
    ]
