# Generated by Django 4.2.4 on 2023-08-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255)),
                ('email_contato', models.EmailField(max_length=255)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Topo',
        ),
        migrations.AddField(
            model_name='imagensdestaque',
            name='descricao_longa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagensdestaque',
            name='descricao_pequena',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
