# Generated by Django 4.2.4 on 2023-08-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens',
            name='i_frame_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
