# Generated by Django 4.2.4 on 2023-08-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_contato_delete_topo_imagensdestaque_descricao_longa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
