# Generated by Django 4.2.4 on 2023-08-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_imagens_i_frame_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='i_frame_1',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
