# Generated by Django 4.2.4 on 2023-08-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_imagens_i_frame_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens',
            name='img_3',
            field=models.ImageField(default=1, upload_to='imagens'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagens',
            name='img_4',
            field=models.ImageField(default=1, upload_to='imagens'),
            preserve_default=False,
        ),
    ]
