# Generated by Django 4.2.4 on 2023-08-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_contato_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='email_contato',
            new_name='email',
        ),
    ]
