# Generated by Django 4.2.4 on 2023-08-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_imagens_img_3_imagens_img_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens',
            name='imagem_tabs',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens'),
        ),
        migrations.AddField(
            model_name='imagens',
            name='imagem_tabs1',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens'),
        ),
        migrations.AddField(
            model_name='imagens',
            name='imagem_tabs2',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='carroucel1',
            field=models.ImageField(upload_to='static/imagens'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='carroucel2',
            field=models.ImageField(upload_to='static/imagens'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='carroucel3',
            field=models.ImageField(upload_to='static/imagens'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='img_1',
            field=models.ImageField(upload_to='static/imagens'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='img_2',
            field=models.ImageField(upload_to='static/imagens'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='img_3',
            field=models.ImageField(upload_to='static/imagens'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='img_4',
            field=models.ImageField(upload_to='static/imagens'),
        ),
    ]
