# Generated by Django 4.2.4 on 2023-08-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_imagens_imagem_tabs_imagens_imagem_tabs1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagens',
            old_name='imagem_tabs',
            new_name='imagem_tabs3',
        ),
    ]
