# Generated by Django 4.2.4 on 2023-08-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_rename_imagem_tabs_imagens_imagem_tabs3'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens',
            name='banner_topo',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens'),
        ),
    ]
