# Generated by Django 4.2.4 on 2023-08-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_imagens_banner_topo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens',
            name='d_curta_1',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagens',
            name='d_curta_2',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagens',
            name='d_curta_3',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagens',
            name='d_maior_1',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagens',
            name='d_maior_2',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagens',
            name='d_maior_3',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
