# Generated by Django 4.2.4 on 2023-08-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_imagens_d_curta_1_imagens_d_curta_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('dt_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='i_frame_1',
        ),
    ]
