# Generated by Django 4.2.4 on 2023-08-05 00:17

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_video_remove_imagens_i_frame_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='dt_upload',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
