# Generated by Django 4.2.4 on 2023-08-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_delete_video_imagens_dt_upload_imagens_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_topo', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='banner_topo',
        ),
    ]
