# Generated by Django 4.2.4 on 2023-08-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_topo_remove_imagens_banner_topo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_tabs1', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
                ('imagem_tabs2', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
                ('imagem_tabs3', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='carroucel1',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='carroucel2',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='carroucel3',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='d_curta_1',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='d_curta_2',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='d_curta_3',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='d_maior_1',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='d_maior_2',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='d_maior_3',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='imagem_tabs1',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='imagem_tabs2',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='imagem_tabs3',
        ),
    ]
