# Generated by Django 4.2.4 on 2023-08-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_tabs_remove_imagens_carroucel1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemLateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(upload_to='static/imagens')),
                ('img_2', models.ImageField(upload_to='static/imagens')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='img_1',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='img_2',
        ),
    ]
