# Generated by Django 4.2.4 on 2023-08-05 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_imagemlateral_remove_imagens_img_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemlateral',
            name='img_2',
        ),
    ]
