# Generated by Django 4.2.4 on 2023-08-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_remove_imagemlateral_img_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemlateral',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens'),
        ),
        migrations.AlterField(
            model_name='imagemlateral',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens'),
        ),
    ]
