# Generated by Django 4.2.4 on 2023-08-05 03:17

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_imagemlateral_img_2_alter_imagemlateral_img_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caurosel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel1', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
                ('carousel2', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
                ('carousel3', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('url', embed_video.fields.EmbedVideoField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='dt_upload',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='imagens',
            name='url',
        ),
        migrations.AlterField(
            model_name='imagens',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagens'),
        ),
    ]
