# Generated by Django 4.2.4 on 2023-08-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_caurosel_video_remove_imagens_dt_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemlateral',
            name='img_2',
        ),
    ]
