# Generated by Django 4.2.4 on 2023-08-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_remove_imagemlateral_img_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgDestaque1', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.DeleteModel(
            name='Imagens',
        ),
    ]
