# Generated by Django 4.2.4 on 2023-08-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_imagensdestaque_delete_imagens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel1', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel2', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel3', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.DeleteModel(
            name='Caurosel',
        ),
    ]
