# Generated by Django 4.2.4 on 2023-08-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_carousel1_decricao_curta_carousel1_decricao_maior_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabsContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabscontato', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='TabsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabsinfo', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='TabsPalestras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabspalestras', models.ImageField(blank=True, null=True, upload_to='static/imagens')),
            ],
        ),
        migrations.DeleteModel(
            name='Tabs',
        ),
    ]
