# Generated by Django 4.2.4 on 2023-08-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_tabscontato_tabsinfo_tabspalestras_delete_tabs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabspalestras',
            old_name='tabspalestras',
            new_name='tabspalestra',
        ),
    ]
